### ISSUE TITLE
Unable to run MongoSwift on iOS simulator

### ISSUE THREAD

**Issue by vichetmeng** [mongodb/mongo-swift-driver#117]
I got this error when I try to make a request to my DB using MongoSwift.

"/usr/local/opt/mongo-c-driver/lib/libbson-1.0.0.dylib: mach-o, but not built for iOS simulator"

**Comment by kmahar** [comment]
Hi @vichetmeng, are you still having problems with this using the latest version of the driver?

**Comment by kmahar** [comment]
Closing as it appears the issue has gone away. Feel free to reopen if needed 🙂

**Comment by Sobios** [comment]
I still get this error libbson-1.0.0.dylib: mach-o, but not built for iOS simulator when I try to run my app in Xcode.

**Comment by kmahar** [comment]
Hi @Sobios! Are you trying to use the driver in an iOS app? We only support MacOS and Linux.

**Comment by Sobios** [comment]
> Hi @Sobios! Are you trying to use the driver in an iOS app? We only support MacOS and Linux.

@kmahar Yes I was trying in iOS app. Okay. thank you for your quick response.

**Comment by kmahar** [comment]
@Sobios Sure thing. For mobile DB purposes, we recommend using Realm 🙂
