### ISSUE TITLE
ObjectId.getTimestamp(): Does not exist for Mongo Mobile for Swift Local-Only Mobile App

### ISSUE THREAD

**Issue by moofus** [mongodb/mongo-swift-driver#155]
### Swift version

What does this command give you?

$ swift --version
Apple Swift version 4.2.1 (swiftlang-1000.0.42 clang-1000.10.45.1)
Target: x86_64-apple-darwin18.0.0

### Operating system

What does this command give you?

$ uname -a
Lamars-iMac:0 moofus$ uname -a
Darwin Lamars-iMac.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

### Driver version

What does this command give you?

$ cat Package.resolved # Applies if you are using Swift package manager
N/A
*or*

$ cat Podfile.lock # Applies if you are using Cocoapods
Lamars-iMac:moofuslist moofus$ cat Podfile.lock 
PODS:
  - mongo-embedded-c-driver (1.13.0-4.0.4)
  - mongo_embedded (4.0.4)
  - mongoc_embedded (4.0.4):
    - mongo-embedded-c-driver (~> 1.13.0-4.0.4)
    - mongo_embedded (~> 4.0.4)
  - MongoMobile (0.0.5):
    - mongo_embedded (~> 4.0.4)
    - mongoc_embedded (~> 4.0.4)
    - MongoSwift (~> 0.0.7)
  - MongoSwift (0.0.7):
    - mongo-embedded-c-driver (~> 1.13.0-4.0.0)
  - StitchCore (4.1.1):
    - StitchCoreSDK (= 4.1.1)
  - StitchCoreLocalMongoDBService (4.1.1):
    - MongoMobile (= 0.0.5)
    - StitchCoreSDK (= 4.1.1)
  - StitchCoreRemoteMongoDBService (4.1.1):
    - StitchCoreSDK (= 4.1.1)
  - StitchCoreSDK (4.1.1):
    - MongoSwift (= 0.0.7)
  - StitchLocalMongoDBService (4.1.1):
    - StitchCore (= 4.1.1)
    - StitchCoreLocalMongoDBService (= 4.1.1)
  - StitchRemoteMongoDBService (4.1.1):
    - StitchCore (= 4.1.1)
    - StitchCoreRemoteMongoDBService (= 4.1.1)
  - StitchSDK (4.1.1):
    - StitchSDK/StitchSDK (= 4.1.1)
  - StitchSDK/StitchRemoteMongoDBService (4.1.1):
    - StitchRemoteMongoDBService (= 4.1.1)
  - StitchSDK/StitchSDK (4.1.1):
    - StitchSDK/StitchRemoteMongoDBService

DEPENDENCIES:
  - StitchLocalMongoDBService (~> 4.1.1)
  - StitchSDK (= 4.1.1)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - mongo-embedded-c-driver
    - mongo_embedded
    - mongoc_embedded
    - MongoMobile
    - MongoSwift
    - StitchCore
    - StitchCoreLocalMongoDBService
    - StitchCoreRemoteMongoDBService
    - StitchCoreSDK
    - StitchLocalMongoDBService
    - StitchRemoteMongoDBService
    - StitchSDK

SPEC CHECKSUMS:
  mongo-embedded-c-driver: b46360baa15fc142baae80628822f26663220bde
  mongo_embedded: e413134eb6b60544e7278add03007f8fe384a00c
  mongoc_embedded: 41aadbb756b07070d6f0471192a84750cb42c580
  MongoMobile: 2fc916b194dc19b9a6b8d948d42441b0b37812e7
  MongoSwift: de22baca5a59aef44de44e07ee9adb8c4f59c5ee
  StitchCore: 341cdc409c52babb505f152a01232ba60cbdee55
  StitchCoreLocalMongoDBService: a76bd6d3fb845158b95e896f638e908dcd65b514
  StitchCoreRemoteMongoDBService: 1eacc874bbc227466951b0eedb44e872efd0459f
  StitchCoreSDK: 3c3cb812dd371d790935f082810e93e9c90727fe
  StitchLocalMongoDBService: 0537b7fc1d9ae69b90eddc28b8dac0c4e3c029d2
  StitchRemoteMongoDBService: ad6bf3d39ceba7f5026f065ea67ba341bc195c2e
  StitchSDK: e291ceeb90f06b8d534ef27b425e3fa7e67d3d57

PODFILE CHECKSUM: 712005c5d18e71d1efd2137a01dacd9892a9c590

COCOAPODS: 1.5.3

### What is the version(s) of `mongod` that you are running with the driver?
Try running:

$ mongod --version
N/A
or, running this in a MongoDB shell connected to the relevant node(s):
N/A
> db.version()
N/A

### What is your server topology?
N/A
How is your MongoDB deployment configured?
N/A

### How did you install `libmongoc` and `libbson` on your system
N/A
Did you use `brew`? Did you install them manually? etc.
No

### Version of `libmongoc` and `libbson`
N/A
What does this command give you?
N/A
$ brew list --versions mongo-c-driver # Applies if you installed via brew
N/A
*or*
N/A
$ apt list --installed | grep -E '(libmongoc|libbson)' # Applies if you installed via apt
N/A
*or*
N/A
$ pkg-config --modversion libmongoc-1.0 # Applies if you use pkg-config
$ pkg-config --modversion libbson-1.0
N/A

## What is the problem? 
ObjectId.getTimestamp(): Does not exist.
Currently there is no way to get the timestamp from the ObjectId.

**BE SPECIFIC**:
* What is the _expected_ behavior and what is _actually_ happening?
* Do you have any particular output that demonstrates this problem?
* Do you have any ideas on _why_ this may be happening that could give us a
clue in the right direction?
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Swift)? 
* Is there a workaround that seems to avoid this this issue?
* Are there multiple ways of triggering this bug (perhaps more than one
function produce a crash)?
* If you know how to reproduce the bug, use the `BugReport` project in our
`Examples/` directory to write some demo code showcasing it so that we have
something to go off of.

## Reproducing the bug

1. First, do this.
2. Then do this.
3. After doing that, do this.
4. And then, finally, do this.
5. Bug occurs.

**Comment by kmahar** [comment]
Hi! Thanks for opening this issue. We've created [SWIFT-265](https://jira.mongodb.org/browse/SWIFT-265) to track this. You can follow its status there going forward.
