### ISSUE TITLE
Conform UUID to BSONValue

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#161]
Currently `UUID` are encoded as `String` because they are `Encodable` that way.

From https://docs.mongodb.com/manual/core/document/#the-id-field
>The following are common options for storing values for _id:
>...
>Generate a UUID in your application code. For a more efficient storage of the UUID values in the collection and in the _id index, store the UUID as a value of the BSON BinData type.
Index keys that are of the BinData type are more efficiently stored in the index if:
>* the binary subtype value is in the range of 0-7 or 128-135, and
>* the length of the byte array is: 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20, 24, or 32.

It would be therefore nice to have a native extension in the driver, that encodes `UUID` as per mongo documentation recommended way instead.

**Comment by kmahar** [comment]
Closing this issue as we've opened [SWIFT-295](https://jira.mongodb.org/browse/SWIFT-295) to track the work.
