### ISSUE TITLE
BSONValue  protocol doesn't return Self

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#164]
I am not sure this is by design but I would expect this protocol method to return `Self` instead.

From `BSONValue.swift`:
`static func from(iterator iter: DocumentIterator) throws -> BSONValue`

This is what makes sense to me:
`static func from(iterator iter: DocumentIterator) throws -> Self`

**Comment by mbroadst** [comment]
@valeriomazzeo could you elaborate on why that would be preferable? I'm sure it's just something we missed when learning Swift if it's indeed the idiomatic preference.

**Comment by mbroadst** [comment]
Ah, after reading more about it this does make sense. The initialized for a DocumentIterator for a given subclass of `BsonValue` should indeed return an instance of the subclass, not any `BsonValue`

**Comment by kmahar** [comment]
Great point @valeriomazzeo. We've opened [SWIFT-278](https://jira.mongodb.org/browse/SWIFT-278) about this, it should be implemented shortly.

**Comment by kmahar** [comment]
fixed by #171.
