### ISSUE TITLE
Mongo shell eval support 

### ISSUE THREAD

**Issue by alicin** [mongodb/mongo-swift-driver#187]
Are there any plans to support evaluating pure javascript code for queries, like in mongo shell?

**Comment by jmikola** [comment]
Are you referring to the [`eval`](https://docs.mongodb.com/manual/reference/command/eval/#dbcmd.eval) database command, which takes Javascript code (i.e. [BSON type](https://docs.mongodb.com/manual/reference/bson-types/) 0x0D or 0x0F) and executes it server-side? If so, that command is deprecated in MongoDB and is unlikely to be introduced into any driver that does not already have a historical helper method (as the shell does with [`db.eval()`](https://docs.mongodb.com/manual/reference/method/db.eval/)).

[`MongoDatabase.runCommand()`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoDatabase.html#/s:10MongoSwift0A8DatabaseC10runCommand_7optionsAA8DocumentVAG_AA03RunE7OptionsVSgtKF) can be used to run arbitrary database commands for which the driver does not have a helper method. You can use that to execute commands such as `eval`, so long as you're willing to construct the command document yourself. The [`CodeWithScope`](https://mongodb.github.io/mongo-swift-driver/Structs/CodeWithScope.html) struct can be used to represent the Javascript BSON type expected for the `eval` field in the command.

On the off chance you were referring to the [`$where`](https://docs.mongodb.com/manual/reference/operator/query/where/) query operator, which allows the server to evaluate Javascript as part of query matching logic, you should have no problems using that in the Swift driver today. Per the documentation, the operator accepts either a string or Javascript type (i.e. CodeWithScope) as its value. AFAIK, that operator is not deprecated in the server.

Note that there is a real cost to evaluating [server-side Javascript](https://docs.mongodb.com/manual/core/server-side-javascript/), so if you can get by using native driver APIs for queries and other operations you will generally be better off. `$where` certainly has its uses (e.g. comparing two fields in the same document with one another), as does `[mapReduce`](https://docs.mongodb.com/manual/reference/command/mapReduce/) (for rare use cases beyond the capabilities of [aggregation](https://docs.mongodb.com/manual/aggregation/)); however, server-side Javascript should not be your first choice without good reason.

Beyond that, I'm not aware of any plans for the Swift driver (or any other driver, excluding Node.js) to evaluate Javascript for client-side queries -- in case that was more of what you had in mind.

**Comment by kmahar** [comment]
I'm going to close this due to inactivity. @alicin please let us know if you have further questions.
