### ISSUE TITLE
IndexOptions var properties

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#211]
It would be nice for `IndexOptions` and any other similar `____Options` data structure to have `var` properties rather than `let`.

Please take as reference https://github.com/asensei/vapor-fluent-mongo/blob/master/Sources/FluentMongo/IndexBuilder.swift

This is what has to be done in order to modify a single field:

```swift
public func unique(_ value: Bool) -> IndexBuilder<T> {
        let previous = self.index.options
        let options = IndexOptions(
            background: previous?.background,
            expireAfter: previous?.expireAfter,
            name: previous?.name,
            sparse: previous?.sparse,
            storageEngine: previous?.storageEngine,
            unique: value,
            version: previous?.version,
            defaultLanguage: previous?.defaultLanguage,
            languageOverride: previous?.defaultLanguage,
            textVersion: previous?.textVersion,
            weights: previous?.weights,
            sphereVersion: previous?.sphereVersion,
            bits: previous?.bits,
            max: previous?.max,
            min: previous?.min,
            bucketSize: previous?.bucketSize,
            partialFilterExpression: previous?.partialFilterExpression,
            collation: previous?.collation
        )
        self.index = IndexModel(keys: self.index.keys, options: options)

        return self
    }
```

**Comment by mbroadst** [comment]
Hi @valeriomazzeo! We actually have a ticket to do this that you can track [here](https://jira.mongodb.org/browse/SWIFT-355). Unfortunately it's not actively scheduled, but pull requests are of course welcome!

**Comment by kmahar** [comment]
I'm going to close this as we have [SWIFT-355](https://jira.mongodb.org/browse/SWIFT-355) tracking the work. Please let us know any other suggestions you have 🙂
