### ISSUE TITLE
Not working in Swift 5.0 and latest Xcode 10.2

### ISSUE THREAD

**Issue by kumarmuthaiah18** [mongodb/mongo-swift-driver#224]
### Swift version

Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0

### Operating system

Darwin Kumar-Muthaiahs-MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

### Driver version

What does this command give you?
lved
{
  "object": {
    "pins": [
      {
        "package": "MongoSwift",
        "repositoryURL": "https://github.com/mongodb/mongo-swift-driver",
        "state": {
          "branch": null,
          "revision": "11a8870f35ac5717057a228f029d31f4481bab6f",
          "version": "0.0.9"
        }
      },
      {
        "package": "Nimble",
        "repositoryURL": "https://github.com/Quick/Nimble.git",
        "state": {
          "branch": null,
          "revision": "e9d769113660769a4d9dd3afb855562c0b7ae7b0",
          "version": "7.3.4"
        }
      },
      {
        "package": "bson",
        "repositoryURL": "https://github.com/mongodb/swift-bson",
        "state": {
          "branch": null,
          "revision": "87b458f55ba66f20305341d9d138e47dbcc92da7",
          "version": "2.0.0"
        }
      },
      {
        "package": "mongoc",
        "repositoryURL": "https://github.com/mongodb/swift-mongoc",
        "state": {
          "branch": null,
          "revision": "e503b50210dae2cf0220474c2f12087830150e9f",
          "version": "2.0.0"
        }
      }
    ]
  },
  "version": 1
}

### What is the version(s) of `mongod` that you are running with the driver?

db version v4.0.2
git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

### What is your server topology?

Going to run in the same machine as the application

### How did you install `libmongoc` and `libbson` on your system

brew

### Version of `libmongoc` and `libbson`
ions mongo-c-driver
mongo-c-driver 1.13.0

## What is the problem? 

I'm first time using the driver.  I don't want to use older swift version and creates problem in Apple Xcode and future my software releases. Work around of using older swift version solves the error, but I don't want the older one, always syncing with Apple release is better to avoid delays.

Error Information:
Use the latest XCode and latest Swift.

Error, like below and similar other errors related to compilation issue. Its big I cannot attach full.

Output: 

.../.build/checkouts/mongo-swift-driver/Sources/MongoSwift/APM.swift:52:91: error: cannot convert value of type 'OpaquePointer' to expected argument type 'UnsafePointer<bson_t>' (aka 'UnsafePointer<_bson_t>')
        self.command = Document(fromPointer: mongoc_apm_command_started_get_command(event)!)

.../.build/checkouts/mongo-swift-driver/Sources/MongoSwift/APM.swift:93:89: error: cannot convert value of type 'OpaquePointer' to expected argument type 'UnsafePointer<bson_t>' (aka 'UnsafePointer<_bson_t>')
        self.reply = Document(fromPointer: mongoc_apm_command_succeeded_get_reply(event)!)
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
## Reproducing the bug

Use the version of Xcode and Swift as mentioned above. Include mongo-swift-deriver in Package.Swift and compile in command line.

**Comment by kumarmuthaiah18** [comment]
Hi any update?

**Comment by kumarmuthaiah18** [comment]
I need to do some decisions based on your support!

**Comment by kumarmuthaiah18** [comment]
If you are busy at least give some feedback, so that the user will find it Kind and Peaceful!

**Comment by patrickfreed** [comment]
Due to some changes to the way C types are imported in Swift 5 and some technicalities of the way libbson was implemented, the driver cannot currently be built with Swift 5.

We're currently looking into solutions for this. In the meantime, you will need to use Swift 4. I'm sorry for any inconvenience this causes.

**Comment by mbroadst** [comment]
Hi @kumarmuthaiah18, as noted in the JIRA ticket you opened we are tracking this work on the [SWIFT-276](https://jira.mongodb.org/browse/SWIFT-276) ticket, and anticipate Swift 5 support in a release this week. Please follow up there with any further questions/concerns. Thank you for your report.

**Comment by kumarmuthaiah18** [comment]
Thanks All! Waiting for the Swift 5 support.
