### ISSUE TITLE
SegFault when instantiating MongoClient in a Docker container

### ISSUE THREAD

**Issue by rkreutz** [mongodb/mongo-swift-driver#270]
### Operating system
MacOS Mojave (10.14.4 (18E227))
```
Darwin Rodrigos-MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

### Driver version
```
{
  "object": {
    "pins": [
      {
        "package": "MongoSwift",
        "repositoryURL": "https://github.com/mongodb/mongo-swift-driver",
        "state": {
          "branch": null,
          "revision": "54bf5bfd8d347160e78e59ef00715400181478dc",
          "version": "0.1.0"
        }
      },
      {
        "package": "Nimble",
        "repositoryURL": "https://github.com/Quick/Nimble.git",
        "state": {
          "branch": null,
          "revision": "43304bf2b1579fd555f2fdd51742771c1e4f2b98",
          "version": "8.0.1"
        }
      },
      {
        "package": "bson",
        "repositoryURL": "https://github.com/mongodb/swift-bson",
        "state": {
          "branch": null,
          "revision": "40f770ed265bb9958edbcd0c809a3c2afe75a3ba",
          "version": "2.1.0"
        }
      },
      {
        "package": "mongoc",
        "repositoryURL": "https://github.com/mongodb/swift-mongoc",
        "state": {
          "branch": null,
          "revision": "e503b50210dae2cf0220474c2f12087830150e9f",
          "version": "2.0.0"
        }
      }
    ]
  },
  "version": 1
}
```

### What is your server topology?

I'm using Docker and `docker-compose` to run a container with the MongoSwift driver and a `mongo:latest` container.

Here is the `Dockerfile` I'm using to generate the Swift driver image (entirely based on the Dockerfile.vapor in the Examples folder):
```
# ---------------------------------------------------------------------------
# Builder container
# ---------------------------------------------------------------------------

# You can set the Swift version to what you need for your app.
# Versions can be found here: https://hub.docker.com/_/swift
FROM swift:4.2 as builder

# For local build, add `--build-arg env=docker`
# In your application, you can use `Environment.custom(name: "docker")` to check if you're in this env
# ARG env

RUN apt-get -qq update && apt-get -q -y install \
  tzdata \
  git cmake libssl-dev libsasl2-dev \
  && rm -r /var/lib/apt/lists/*

# Compiling latest libmongoc and libbson
RUN git clone -b r1.13 https://github.com/mongodb/mongo-c-driver /tmp/libmongoc
WORKDIR /tmp/libmongoc
RUN cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=/usr \
  -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF \
  -DCMAKE_BUILD_TYPE=Release
RUN make -j8 install

WORKDIR /app
COPY . .
RUN mkdir -p /build/lib && cp -R /usr/lib/swift/linux/*.so /build/lib
RUN swift build -c release && mv `swift build -c release --show-bin-path` /build/bin

# ---------------------------------------------------------------------------
# Production image
# ---------------------------------------------------------------------------

FROM ubuntu:16.04

RUN apt-get -qq update && apt-get install -y \
  libicu55 libxml2 libbsd0 libcurl3 libatomic1 \
  tzdata \
  git cmake libssl-dev libsasl2-dev \
  && rm -r /var/lib/apt/lists/*

# Compiling latest libmongoc and libbson
RUN git clone -b r1.13 https://github.com/mongodb/mongo-c-driver /tmp/libmongoc
WORKDIR /tmp/libmongoc
RUN cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=/usr \
  -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF \
  -DCMAKE_BUILD_TYPE=Release
RUN make -j8 install

WORKDIR /app
COPY --from=builder /build/bin/Run .
COPY --from=builder /build/lib/* /usr/lib/

EXPOSE 8080
ENTRYPOINT ./Run
```

And here is the `docker-compose.yml` to run the Swift driver and the MongoDB instance:
```
version: "2.0"
services:
  mongoswift:
    container_name: mongoswift
    restart: always
    build: ./
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - "27018:27017" # I've had another instance of mongod running locally, so I've switched the exposed port
```

### Docker version
`Docker version 18.09.2, build 6247962`
### Docker Compose version
`docker-compose version 1.23.2, build 1110ad01`

### How did you install `libmongoc` and `libbson` on your system

Using the Dockerfile (based on Dockerfile.vapor on this repo). Building it from source code in the Dockerfile.

## What is the problem? 

Whenever I try running the driver using Docker I get a SegFault just by creating an instance of `MongoClient`. It seems the issue arises when the code reaches [here](https://github.com/mongodb/mongo-swift-driver/blob/e83f3c4c4c88d56dcb3ee955eaff4e30a12f1219/Sources/MongoSwift/MongoClient.swift#L177).

I'm using a really simple Swift Application:

### Package.swift
```swift
import PackageDescription

let package = Package(
    name: "Teste",
    products: [],
    dependencies: [
        .package(url: "https://github.com/mongodb/mongo-swift-driver", .upToNextMajor(from: "0.1.0"))
    ],
    targets: [
        .target(name: "Run", dependencies: ["MongoSwift"])
    ]
)
```
### Sources/Run/main.swift
```swift
import MongoSwift
import Foundation

do {
   _ = try MongoClient("mongodb://mongo:27017") // mongo should be resolved to the mongod instance running in the Docker container mongo
   print("All went well")
} catch {
   print(String(describing: error))
}
```

Any help would be much appreciated. Thanks

## Reproducing the bug

1. Add the files in a temporary folder with the given structure:
```
|-- Dockerfile
|-- docker-compose.yml
|-- Package.swift
|-- Package.resolved
|-- Sources
    |-- Run
        |-- main.swift
```
2. Run `docker-compose build`, the Swift driver container should build.
3. Run `docker-compose up`, the containers should be started.
4. You'll see the mongo container is up and running, but the `mongoswift` container will be throwing a SegFault and exiting with: `mongoswift exited with code 139`

Thanks

**Comment by kmahar** [comment]
Hello @rkreutz! Thank you for this very detailed report. I have never used Docker before but I was able to reproduce this issue in just a few minutes. 🙂 

The issue here is that the Dockerfile builds libmongoc with AUTOMATIC_INIT_AND_CLEANUP=OFF (which is recommended), but you are not calling `MongoSwift.initialize()` before you create a client. That ultimately calls through to `mongoc_init` which sets up some global state etc. used by libmongoc.

Adding a call to `MongoSwift.initialize()` before creating the client solves the crash for me:
```swift
import MongoSwift
import Foundation

do {
   MongoSwift.initialize()
   _ = try MongoClient("mongodb://mongo:27017") // mongo should be resolved to the mongod instance running in the Docker container mongo
   print("All went well")
} catch {
   print(String(describing: error))
}
```

Try that out and let us know if it works for you?

**Comment by rkreutz** [comment]
Hey @kmahar! That was fast, thanks a lot, it worked like a charm.

Is there anything else I should know about `MongoSwift.initialize()` method?

Thanks

**Comment by kmahar** [comment]
@rkreutz glad to hear it!

Couple things:
1. We've found that the issue you ran into here is pretty common, i.e. a lot of users don't remember to call this method. For that reason, we recently updated the code such that the `MongoClient` initializer will take care of the one-time initialization for you if it's needed. In our upcoming patch release, this method will be deprecated and calling it will have no effect, and it will be removed altogether down the road. Sorry for the inconvenience of having to add this to your code vjust to remove it again soon.

2. The symmetric method to this is `MongoSwift.cleanup()`. (This is going to be deprecated in favor of `cleanupMongoSwift()` in the next release.) It's recommended to call this when your application is terminating to clean up global state/resources.

**Comment by rkreutz** [comment]
> We've found that the issue you ran into here is pretty common, i.e. a lot of users don't remember to call this method. For that reason, we recently updated the code such that the MongoClient initializer will take care of the one-time initialization for you if it's needed. In our upcoming patch release, this method will be deprecated and calling it will have no effect, and it will be removed altogether down the road. Sorry for the inconvenience of having to add this to your code vjust to remove it again soon.

That's completely understandable, don't worry about.

> The symmetric method to this is MongoSwift.cleanup(). (This is going to be deprecated in favor of cleanupMongoSwift() in the next release.) It's recommended to call this when your application is terminating to clean up global state/resources.

Good to know. What would be the side effects of not calling `cleanup()` or (`cleanupMongoSwift()` in the future)? I'm asking cause I'm using a shared `MongoClient` in my server and since it is supposed to be running all the time there wouldn't be a point where I'd do the clean up (at least I can't think of anywhere to do the cleanup) however the server might crash/go down/whatever which then would start the `.initialize()` again. So do you know if there could be any issues from the server going down unexpectedly and then calling again `.initialize()` without the `.cleanup()`?

Thanks once again

**Comment by kmahar** [comment]
In that case, it should be fine to skip calling `cleanup` . If the server is crashing/shutting down, all the memory/resources will be freed when that happens anyway.

Side note, not sure how exactly you are sharing the `MongoClient`, but just FYI currently that type is not threadsafe. We have work in progress at the moment so that `MongoClient` (and `MongoDatabase` and `MongoCollection`) will become threadsafe. I don't think it will make it into the next release, but the one after. You can track the work [here](https://jira.mongodb.org/browse/SWIFT-66).

**Comment by rkreutz** [comment]
🤔 good to know, I was assuming it was thread safe, in that case I think I’ll just create a new client for each request for simplicity, it didn’t seem to have that much memory overhead.

Actually do you guys have any recommended way of dealing with the client, like either creating it every time you need it or sharing it across the application? (I’m guessing it’s the first, but curious to know)

**Comment by kmahar** [comment]
Yes, at this time our recommendation would be to just use one client per request.

**Comment by rkreutz** [comment]
Perfect, thanks for the info and the help. Feel free to close this as well. Thanks

**Comment by kmahar** [comment]
My pleasure, please feel free to reach out with any other questions, issues, or suggestions.
