### ISSUE TITLE
file mongoc.h not found on macOS but mongo-c-driver-1.15.1 is installed

### ISSUE THREAD

**Issue by MadGeorge** [mongodb/mongo-swift-driver#324]
## What is the problem? 

After including mongo-swift-driver 0.1.3 into Package.swit i got Xcode build error `mongoc.h file not found` 

After some research i found mongoc.h location on my mac disc. The path is `/usr/local/Cellar/mongo-c-driver/1.15.1/include/libmongoc-1.0/mongoc.h`

I set **Library Search Path** to `/usr/local/Cellar` recursive and previous error was gone, but now i have `'cstddef.h' file not found`referenced from `Node.h`.

It looks like i missed something but i can not figure out how to setup this dependency correctly.

I tried to install `MongoKitten` and was builds just fine. I may try proces to work with MongoKitten, but i do not like their api and struggle to Document object modeling, so it will be nice some one can help me to resolve build issue with `mongo-swift-driver`.

### Xcode version
Version 11.0 (11A420a)

### Swift version
5.1

### Operating system
```
$ uname -a
Darwin imaciosdev.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

### Driver version

What does this command give you?
```
$ cat Package.resolved 
it's too long to be here. but it's fine, trust me.
```

### What is the version(s) of `mongod` that you are running with the driver?

```
$ mongod --version
db version v3.6.5
git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
OpenSSL version: OpenSSL 1.0.2s  28 May 2019
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

### What is your server topology?
MongoDB installed via brew and just launched on localhost. I can easily access it via `mongodb://localhost:27017`

### How did you install `libmongoc` and `libbson` on your system
via homebrew

### Version of `libmongoc` and `libbson`

```
$ brew list --versions mongo-c-driver 
mongo-c-driver 1.15.1
```

**Comment by kmahar** [comment]
Hi @MadGeorge, thanks for opening this issue.
I'm not able to reproduce this locally, but it seems like the issue is potentially with some missing C header files on your machine. Could you try following the instructions on [this page](https://donatstudios.com/MojaveMissingHeaderFiles) and see if it resolves your issues? 

Let me know how it goes.

**Comment by MadGeorge** [comment]
@kmahar thank you for the help.

Command
```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
``` 
did the trick and Xcode may build project without additional setup.
I do not know how i missed that blog post, i googled "xcode missing headers" and "macos missing headers" many times but just blind to see this site.

Thank you for this link and for your contribution to this library.

**Comment by kmahar** [comment]
@MadGeorge I'm glad that resolved it!

My pleasure. Please don't hesitate to reach out if you have any questions or encounter any other issues going forward.
