### ISSUE TITLE
Users and Roles collections

### ISSUE THREAD

**Issue by adamofsky** [mongodb/mongo-swift-driver#342]
Hello
There is any way to use features described here [https://docs.mongodb.com/manual/reference/method/js-user-management/](url) and here [https://docs.mongodb.com/manual/reference/method/js-role-management/](url)
If yes so there is any way to use it like a Service in Vapor?
Thank you for help
Regards

**Comment by patrickfreed** [comment]
The driver currently does not have any high-level helpers for users/roles management, but the same things can be achieved via the generic [`runCommand`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoDatabase.html#/s:10MongoSwift0A8DatabaseC10runCommand_7options7sessionAA8DocumentVAH_AA03RunE7OptionsVSgAA13ClientSessionCSgtKF) method on `MongoDatabase`.
e.g.
```swift
try db.runCommand([
    "createUser": "username",
    "pwd": "hello"
    "roles": [
         [ "role": "read", "db": "reporting" ] as Document
    ]
])
```
Given that swift can be used in a repl and therefore as a shell replacement, it may be useful for us to provide a higher level API for user/role management. I've filed a [ticket](https://jira.mongodb.org/browse/SWIFT-649) about supporting this in a future version in the driver.

We have [an example](https://github.com/mongodb/mongo-swift-driver/tree/master/Examples/Vapor) of general usage of MongoSwift with Vapor, but there isn't currently an integration with the Vapor services API. There is a [Fluent wrapper around the driver](https://github.com/asensei/vapor-fluent-mongo) that is currently being written though, so you may want to check that out.

**Comment by patrickfreed** [comment]
Closing this for now--let us know if you have any further questions!
