### ISSUE TITLE
Documentation and Examples are Insufficient 

### ISSUE THREAD

**Issue by gurugeek** [mongodb/mongo-swift-driver#361]
### Swift version

What does this command give you?
```
5.1.2
```

### Operating system

```
19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_64

```

### Driver version
```
0.1.3
```

### What is the version(s) of `mongod` that you are running with the driver?

```
db version v4.2.1
```

## What is the problem? 

Documentation is missing common examples e.g. deleteOne is not mentioned, no examples with loops and how to use the data in common templates like stencil or leaf (vapor) are present. Server-site swift might not be the priority but since both major platform are mentioned the examples have to show a minimal functionality. 
For both Kitura (what I am currently using) and Vapor the examples only have a fetch all option.  I think that a CRUD example is very necessary.

**Comment by kmahar** [comment]
Hi @gurugeek, thanks for reaching out. The driver is still in a beta state and we are continually working on improving our documentation.

There is documentation on the `deleteOne` method available [here](https://mongodb.github.io/mongo-swift-driver/Classes/MongoCollection.html#/s:10MongoSwift0A10CollectionC9deleteOne_7options7sessionAA12DeleteResultVSgAA8DocumentV_AA0H7OptionsVSgAA13ClientSessionCSgtKF). An example of using it would be:
```swift
let client = try MongoClient()
let collection = client.db("test").collection("example")
// insert a doc
try collection.insertOne( "a": 1, "b": 2])
// delete the same doc
let result = try collection.deleteOne(["a": 1])
print(result?.deletedCount) // prints 1
```

By loops, do you mean`EventLoop`s? 

We are focusing on server-side usage almost exclusively in fact, and our next release will include an asynchronous SwiftNIO-based API which should integrate nicely with server-side Swift frameworks. You can read a bit more about that [here](https://forums.swift.org/t/officially-supported-mongodb-driver/30324).

I've opened a [JIRA ticket](https://jira.mongodb.org/browse/SWIFT-683) about expanding these examples as you suggest. Feel free to comment here or there with any other suggestions for what you'd like to see in the Vapor and Kitura examples.

**Comment by gurugeek** [comment]
hello @kmahar  thank you for your prompt reply. I did manage find my way through the main crud operations. deleteOne  way easy, for edit I did manage to work this out with $set

> 
>  router.post("/007/edit/:slug") { request, response, next in
>                let page = try request.read(as: Pages.self)
>             let query: Document = ["slug":  page.slug]
>         
>         let doc :  Document =  ["$set": [ "title":  page.title ,"slug": page.slug, "body": page.body,"date": page.date]as Document]
> 
once I am finished with this small project I will probably write some examples on my blog. My report was mostly for the community and for making usage more approachable. 

For loops I meant 

> try collection.find()
requires a simple loop 

> for d in documents {
>                print(d)
>             pages.append(["title" : d.title, "slug" : d.slug, "body": d.body, "date": d.date
>             ])
(which was not really documented anywhere) but more tricky if I run 

```
let query: Document = ["slug": name]
        
        let collection = try MongoClient().db("home").collection("pages", withType: Pages.self)
     let documents = try collection.find(query)
```
documents still requires some looping even if I have a single record.  Without doubts much of the issues are due to my limited knowledge of swift server side but case in point some CRUD examples would go a long way to make everything easier from whomever is used to other libraries or SQL databases.

Thanks again.

**Comment by kmahar** [comment]
Cool! We would definitely be interested in seeing any blog posts you write involving the driver.

We do have an example of using a cursor in our [README](https://github.com/mongodb/mongo-swift-driver#find-documents) but we should integrate it with our Kitura and Vapor examples as well.

For the single record case we currently have work in progress to add a `findOne` method which you may find helpful once it's released.

I'm going to close the issue for now - please feel free to reach out with any feedback or questions going forward. Thanks!
