### ISSUE TITLE
crashes with concurrent connection on OS X: mongoc-socket.c:592 mongoc_socket_errno(): precondition failed: sock

### ISSUE THREAD

**Issue by gurugeek** [mongodb/mongo-swift-driver#366]
### Swift version

What does this command give you?
```
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0
```

### Operating system

What does this command give you?
```
Darwin Davids-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_6
```

### Driver version

What does this command give you?
```
   "version": "0.1.3"
```

### What is the version(s) of `mongod` that you are running with the driver?
Try running:
```
db version v4.2.1
git version: edf6d45851c0b9ee15548f0f847df141764a317e
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

### How did you install `libmongoc` and `libbson` on your system

brew

### Version of `libmongoc` and `libbson`

What does this command give you?
```
mongo-c-driver 1.15.1
```

## What is the problem? 

code, a simple Route with Kitura framework:

```
router.get("/:name") {request, response, next
        
        in guard let name = request.parameters["name"]
        else {
            _ = response.send(status: .badRequest)
            return next()
        }
        let query: Document = ["slug": name]
        let documents = try collection.find(query)
        // check if an error occurred while iterating the cursor
        if let error = documents.error { throw error
        }
        print("documents")
        print(documents)

        var page: [String: String] = [:]
        for d in documents {
            print(d)
            page = [
                "title": d.title,
                "slug": d.slug,
                "body": d.body,
                "date": d.date,
            ]
            break
        }

        if page.isEmpty {
            // response.send ("<h1>&#127934  not found </h1>")

            let title = ["title": "Page not Found - 404 "]
            try response.render("404.stencil", context: title)
            next()
        } else {
            try response.render("page.stencil", with: page)
            response.status(.OK)
        }
    }

```

runs fine without concurrent connections. A simple test with apache benchmark
ab -n 100 -c 10 http://127.0.0.1:8080/index

triggers the crash 

## Reproducing the bug

a) Kitura route as above (select a document from a database)
b) swift run  ( all will work fine here )

c) ab -n 100 -c 10 http://127.0.0.1:8080/index

tennispress(29320,0x70000e8f4000) malloc: *** error for object 0x7fcbc6f0d500: pointer being freed was not allocated
/tmp/mongo-c-driver-20191012-15830-w8k4qd/mongo-c-driver-1.15.1/src/libmongoc/src/mongoc/mongoc-socket.c:592 mongoc_socket_errno(): precondition failed: sock
tennispress(29320,0x70000e977000) malloc: *** set a breakpoint in malloc_error_break to debug
tennispress(29320,0x70000e8f4000) malloc: *** set a breakpoint in malloc_error_break to debug
tennispress(29320,0x70000e76b000) malloc: *** set a breakpoint in malloc_error_break to debug
fish: 'swift run' terminated by signal SIGABRT (Abort)

P.S. it might well be that the problem is in my code, I just find it very difficult to use this with limited documentation

**Comment by kmahar** [comment]
please see the discussion [here](https://github.com/mongodb/mongo-swift-driver/issues/352#issuecomment-558260387) about using the driver in multithreaded contexts.

**Comment by gurugeek** [comment]
@kmahar thanks for letting me know, you might want to remove "///   `MongoCollection` is safe to share across threads." in the Kitura example..

**Comment by kmahar** [comment]
@gurugeek, yes sorry about the misleading comment there. we put it there in preparation for the next release where it will indeed be thread-safe, but as I mentioned on the other ticket that release has been held up for a while and we never reverted the update to the example. I've opened #367 to remove the comment until we do the release.
will close this now, let us know if you have further questions.
