### ISSUE TITLE
How to work with the type ObjectId and how to decode it

### ISSUE THREAD

**Issue by lsca94** [mongodb/mongo-swift-driver#407]
### Swift version

```
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.2.0
```

### Operating system

What does this command give you?
```
Darwin Kernel Version 19.2.0
```

### Driver version

What does this command give you?
```
      {
        "package": "MongoSwift",
        "repositoryURL": "https://github.com/mongodb/mongo-swift-driver",
        "state": {
          "branch": null,
          "revision": "1b38ca8987d1938e0c9245f959fa2172b13cba60",
          "version": "0.2.0"
        }
```

### What is the version(s) of `mongod` that you are running with the driver?

```
db version v4.2.3
```

### What is your server topology?

Single mongodb server running locally

### How did you install `libmongoc` and `libbson` on your system

Installation using brew

### Version of `libmongoc` and `libbson`

```
mongo-c-driver 1.16.1
```

## What is the problem? 

I am currently using the mongo-swift-driver for a project in Vapor but I have some trouble using the ObjectId struct. I didn't find any documentation or Code examples where this problem has been discussed.
So I have a class that looks like this.
```swift
final class InventoryItem: Content {
   let _id: ObjectId 
   var name: String
}
```

I can fetch data from my MongoDB with this command
```swift
let collection = client.db("myDatabase").collection("inventory", withType: InventoryItem.self)
let cursor = try collection.find()
var inventory: [InventoryItem] = []
for c in cursor {
   inventory.append(c)
}
```
And all InventoryItem's are in the variable `inventory`

Now I want to return the data in `inventory` to the client that send a `GET` request.
But the `_id` attribute is of type `ObjectId` and can't be send as JSON. And converting the array `inventory` to JSON gives me errors because the type `ObjectId` does only support BSONEncoder and BSONDecoder.

Now my question is, how can I convert `inventory` to JSON and send it back to the Client. I assume using `BSONDecoder` but I couldn't figure out how. Currently I am parsing all `InventoryItem` to a struct named `InventoryItemJson` that looks like this
```swift
struct InventoryItemJson {
   let _id: String
   var name: String
}
```
And this works for me but it doesn't seem like the correct solution.

**Comment by kmahar** [comment]
Hi @lsca94 ! Thank you for reaching out.

What I would recommend for now is the doing something like the following using `BSONEncoder`:

```swift
let documents = try BSONEncoder().encode(inventory) // create an array of documents equivalent to your structs
let json = documents.description // get JSON string description of the array 
```

This works for now because the string `description` of a `Document` is its extended JSON representation (the [`extendedJSON` property](https://mongodb.github.io/mongo-swift-driver/Structs/Document.html#/s:10MongoSwift8DocumentV12extendedJSONSSvp)), and so the `description` of a `[Document]` ends up being a JSON array.

However, this is not a great workaround. I have opened a JIRA ticket suggesting we add formal support for this in the driver: [SWIFT-726](https://jira.mongodb.org/browse/SWIFT-726).

**Comment by kmahar** [comment]
Also BTW, if you don't need to do anything with the `InventoryItem` structs, you could just use the raw `Document` type with your collection:
```swift
let collection = client.db("myDatabase").collection("inventory")
```

And then you will get `Document`s back from the cursor and you can skip the `BSONEncoder` step to convert the `InventoryItem`s to `Document`s.

**Comment by lsca94** [comment]
Hey @kmahar thanks for your fast reply and for opening the ticket!
I tried your solution and it seems to work. But the ID in the JSON response looks like this 
```JSON
"_id" : { "$oid" : "5e4c52115a04d760a23a2fd2" }
```
Is this the desired behaviour? I thought the `_id` should be easier to handle and just be a string represented like this in JSON
```JSON
"_id" : "5e4c52115a04d760a23a2fd2"
```
I wouldn't want to implement ObjectId on the client side of the application.

**Comment by kmahar** [comment]
So MongoDB uses a special version of JSON called [extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json) which allows us to preserve type information in the JSON. The format you show there `{ "$oid" : "5e4c52115a04d760a23a2fd2" }` is how we indicate that a given property is an ObjectId and not just some string property. This is useful for e.g. round-tripping a document through JSON.

If you want to perform the transformation before sending the data to the client, you could consider mutating the `_id`s on the `Document`s before converting to JSON, doing something like:
```swift
let documents = try BSONEncoder().encode(inventory).map { doc in
    doc["_id"] = doc["_id"]?.objectIdValue?.hex
    return doc
}
```

**Comment by lsca94** [comment]
Thanks for the clarifictions!
I am now closing the Issue.
