### ISSUE TITLE
`swift package update` fails with  `'mongoc' could not be found`

### ISSUE THREAD

**Issue by Rep2** [mongodb/mongo-swift-driver#448]
## Information

`swift package update` fails with `https://github.com/mongodb/swift-mongoc @ 2.0.0: error: manifest parse error: target 'mongoc' referenced in product 'mongoc' could not be found` 

Seems related to https://github.com/mongodb/swift-mongoc/issues/2

### Swift version

```
Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.3.0
```

Tested with multiple Swift versions 5.0 - 5.2.1.

### Operating system

macOS Catalina and Ubuntu 18.04

### Driver version

```
{
  "object": {
    "pins": [
      {
        "package": "Auth",
        "repositoryURL": "https://github.com/vapor/auth.git",
        "state": {
          "branch": null,
          "revision": "e6f61b403727ec124214beb3e57deff579f31d00",
          "version": "2.0.4"
        }
      },
      {
        "package": "Console",
        "repositoryURL": "https://github.com/vapor/console.git",
        "state": {
          "branch": null,
          "revision": "74cfbea629d4aac34a97cead2447a6870af1950b",
          "version": "3.1.1"
        }
      },
      {
        "package": "Core",
        "repositoryURL": "https://github.com/vapor/core.git",
        "state": {
          "branch": null,
          "revision": "1782c550512dc5a43d0bca405e28fc386d932bbf",
          "version": "3.10.0"
        }
      },
      {
        "package": "Crypto",
        "repositoryURL": "https://github.com/vapor/crypto.git",
        "state": {
          "branch": null,
          "revision": "df8eb7d8ae51787b3a0628aa3975e67666da936c",
          "version": "3.3.3"
        }
      },
      {
        "package": "DatabaseKit",
        "repositoryURL": "https://github.com/vapor/database-kit.git",
        "state": {
          "branch": null,
          "revision": "8f352c8e66dab301ab9bfef912a01ce1361ba1e4",
          "version": "1.3.3"
        }
      },
      {
        "package": "Fluent",
        "repositoryURL": "https://github.com/vapor/fluent.git",
        "state": {
          "branch": null,
          "revision": "783819d8838d15e1a05b459aa0fd1bde1e37ac26",
          "version": "3.2.1"
        }
      },
      {
        "package": "FluentSQLite",
        "repositoryURL": "https://github.com/vapor/fluent-sqlite.git",
        "state": {
          "branch": null,
          "revision": "c32f5bda84bf4ea691d19afe183d40044f579e11",
          "version": "3.0.0"
        }
      },
      {
        "package": "HTTP",
        "repositoryURL": "https://github.com/vapor/http.git",
        "state": {
          "branch": null,
          "revision": "fba1329cd430e2f9a3f995b317b04f268d8b2978",
          "version": "3.3.2"
        }
      },
      {
        "package": "Multipart",
        "repositoryURL": "https://github.com/vapor/multipart.git",
        "state": {
          "branch": null,
          "revision": "a7e0db512ff7eee7cd91d0a69dfeeec36f74d604",
          "version": "3.1.2"
        }
      },
      {
        "package": "Pagination",
        "repositoryURL": "https://github.com/vapor-community/pagination.git",
        "state": {
          "branch": null,
          "revision": "0cd6a77687030fd28319bda1945004994c09d430",
          "version": "1.0.9"
        }
      },
      {
        "package": "Routing",
        "repositoryURL": "https://github.com/vapor/routing.git",
        "state": {
          "branch": null,
          "revision": "d76f339c9716785e5079af9d7075d28ff7da3d92",
          "version": "3.1.0"
        }
      },
      {
        "package": "Service",
        "repositoryURL": "https://github.com/vapor/service.git",
        "state": {
          "branch": null,
          "revision": "fa5b5de62bd68bcde9a69933f31319e46c7275fb",
          "version": "1.0.2"
        }
      },
      {
        "package": "SQL",
        "repositoryURL": "https://github.com/vapor/sql.git",
        "state": {
          "branch": null,
          "revision": "50eaeb8f52a1ce63f1ff3880e1114dd8757a78a6",
          "version": "2.3.2"
        }
      },
      {
        "package": "SQLite",
        "repositoryURL": "https://github.com/vapor/sqlite.git",
        "state": {
          "branch": null,
          "revision": "314d9cd21165bcf14215e336a23ff8214f40e411",
          "version": "3.2.1"
        }
      },
      {
        "package": "swift-nio",
        "repositoryURL": "https://github.com/apple/swift-nio.git",
        "state": {
          "branch": null,
          "revision": "8da5c5a4e6c5084c296b9f39dc54f00be146e0fa",
          "version": "1.14.2"
        }
      },
      {
        "package": "swift-nio-ssl",
        "repositoryURL": "https://github.com/apple/swift-nio-ssl.git",
        "state": {
          "branch": null,
          "revision": "0f3999f3e3c359cc74480c292644c3419e44a12f",
          "version": "1.4.0"
        }
      },
      {
        "package": "swift-nio-ssl-support",
        "repositoryURL": "https://github.com/apple/swift-nio-ssl-support.git",
        "state": {
          "branch": null,
          "revision": "c02eec4e0e6d351cd092938cf44195a8e669f555",
          "version": "1.0.0"
        }
      },
      {
        "package": "swift-nio-zlib-support",
        "repositoryURL": "https://github.com/apple/swift-nio-zlib-support.git",
        "state": {
          "branch": null,
          "revision": "37760e9a52030bb9011972c5213c3350fa9d41fd",
          "version": "1.0.0"
        }
      },
      {
        "package": "TemplateKit",
        "repositoryURL": "https://github.com/vapor/template-kit.git",
        "state": {
          "branch": null,
          "revision": "4370aa99c01fc19cc8272b67bf7204b2d2063680",
          "version": "1.5.0"
        }
      },
      {
        "package": "URLEncodedForm",
        "repositoryURL": "https://github.com/vapor/url-encoded-form.git",
        "state": {
          "branch": null,
          "revision": "20f68fbe7fac006d4d0617ea4edcba033227359e",
          "version": "1.1.0"
        }
      },
      {
        "package": "Validation",
        "repositoryURL": "https://github.com/vapor/validation.git",
        "state": {
          "branch": null,
          "revision": "4de213cf319b694e4ce19e5339592601d4dd3ff6",
          "version": "2.1.1"
        }
      },
      {
        "package": "Vapor",
        "repositoryURL": "https://github.com/vapor/vapor.git",
        "state": {
          "branch": null,
          "revision": "642f3d4d1f0eafad651c85524d0d1c698b55399f",
          "version": "3.3.3"
        }
      },
      {
        "package": "WebSocket",
        "repositoryURL": "https://github.com/vapor/websocket.git",
        "state": {
          "branch": null,
          "revision": "d85e5b6dce4d04065865f77385fc3324f98178f6",
          "version": "1.1.2"
        }
      }
    ]
  },
  "version": 1
}
```

### What is the version(s) of `mongod` that you are running with the driver?

```
db version v4.2.3
git version: 6874650b362138df74be53d366bbefc321ea32d4
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

### What is your server topology?

Local database.

## What is the problem? 

See info. The error seems to happen on a clean Swift Package Manager update.

## Reproducing the bug

1. Create a new Swift project that uses Swift Package Manager to handle dependencies.
2. Add `mongo-swift-driver` as a dependency.
`.package(url: "https://github.com/mongodb/mongo-swift-driver.git", from: "0.2.0")`

3. Run `swift package update`
4. Bug occurs.

**Comment by kmahar** [comment]
Hi @Rep2 thanks for reaching out!

I can confirm that I can reproduce this with Swift 5.2. However, I'm not able to reproduce it with Swift 5.0 or 5.1. How are you switching Swift versions to test that? (I'm using swiftenv myself.) 

As it stands, I think 0.2.0 does not support 5.2, I think due to some change in the expected format of system library dependencies. 

If possible I'd recommend using version 1.0.0-rc0 of the driver, which does support 5.2 and relies on a vendored copy of libmongoc rather than the system library package. Though if you still need to use Vapor 3 that won't compile due to the mismatch in SwiftNIO version (Vapor 3 uses SwiftNIO 1, we use SwiftNIO 2.)

**Comment by Rep2** [comment]
Thanks @kmahar, you're correct, using older Swift versions resolved my issue. I was probably switching the Swift version incorrectly.

**Comment by valeriomazzeo** [comment]
@kmahar is there any way to make v0.2 compatible with Swift 5.2?

We are stuck in a limbo where we cannot upgrade to MongoSwift v1.0 because we are still on Vapor 3.

In order to update to Vapor 4, we would need to rewrite our Mongo/Fluent/Driver using MongoSwift v1.0. Performing both migrations is a ton of work to tackle at one time.

Staying on Swift 5.1 is not really an option. Any suggestion?

**Comment by kmahar** [comment]
@valeriomazzeo We can tag an 0.3.0 release for you which would just be 0.2.0 but updated to link to system libmongoc/libbson in the newer way which 5.2 allows. I believe this should be fairly straightforward. I've opened [SWIFT-823](https://jira.mongodb.org/browse/SWIFT-823) to track the work. Will aim to get this out as soon as we can.

**Comment by valeriomazzeo** [comment]
That would be great! 🙌🏻

**Comment by chrisschlitt** [comment]
Has that been tagged yet? I'm also running into the same issue

**Comment by kmahar** [comment]
@chrisschlitt Hasn't been tagged yet sorry - I'll post here and resolve this issue when it is. If you'd like you can also subscribe to get notification when we tag a new release by clicking the "Watch" button and then "Releases only"!

**Comment by AlekseiR** [comment]
Could you explain how to switch to swift 5.1.3 and use driver version 0.2.0 having later swift interpreter?
We are having an issue of 2 different build environments with xCode 11.3.1, swift 5.1.3 and 11.4, swift 5.2.
I am successfully using 0.2.0 with swift 5.1.3, but my friend can not build it

**Comment by kmahar** [comment]
Hi all! 

I've just tagged [v0.3.0](https://github.com/mongodb/mongo-swift-driver/releases/tag/v0.3.0). Please check out the release notes. Hopefully this provides you all with a smoother upgrade path to Swift 5.2 / Vapor 4 / driver 1.0.

@AlekseiR, please try out the new version and see if it resolves your friend's issue.

I'm going to go ahead and close out this issue as the original issue was resolved, but please feel free to reach out if you have any questions or run into further issues.

**Comment by chrisschlitt** [comment]
Thank you for tagging! I'm now able to add it to my swift 5.2 project successfully. However when trying to build the project the build of MongoSwift fails with
`Cannot load module 'BSON' as 'bson'`
Do I need to somehow install a dependency? Or is this a separate issue entirely?
