### ISSUE TITLE
Unit Tests Failing: macOS 10.13.4

### ISSUE THREAD

**Issue by dlbuckley** [mongodb/mongo-swift-driver#48]
I have checked out the latest commit on the `master` branch (1a0afb84198ab870dd33f357e8646f606fc9cb09) and found that the unit tests are failing on macOS 10.13.4 using Xcode 9.2. I assume that since the code is in the `master` branch they should be passing.

<img width="416" alt="screen shot 2018-04-10 at 08 06 44" src="https://user-images.githubusercontent.com/349373/38541223-50c193de-3c96-11e8-8177-3a8be259125c.png">

**Steps Performed**

1) Checkout master branch
2) Install mongo c driver by using `brew install mongo-c-driver`
3) Run `swift package generate-xcodeproj`
4) Selected 'My Mac' as the deployment target
5) Run the unit tests

**Environment**

OS: macOS 10.13.4
IDE: Xcode 9.2

**Comment by kmahar** [comment]
Hi there! Are you running a local mongod instance on the default port (27017)? We should clarify in our README that this is required for most of the tests. :)

Also, some of the failing tests that don't need a mongod rely on relative file paths to retrieve JSON data (for ex., the BSON benchmarks), which I'm not sure Xcode understands - we typically build and test from the command line with `make` and `make test`.

**Comment by dlbuckley** [comment]
I was running Mongo in a local docker container with the ports mapped.

I must admit I totally missed the `Makefile` in the repo. After having a quick look around I ran the tests through `make` and it all worked fine. I guess it's just a bit unusual to have a swift project that relies on `make` rather than having everything run through Xcode. I can see why this is done for the benchmarking suite though as it has to conform to the standard benchmarking suite guidelines and XCTest's performance metrics aren't flexible enough for that.

I guess it's probably just something that needs to be added to the `README.md` so my mistake isn't repeated. Thanks for clarifying!

**Comment by mbroadst** [comment]
@dlbuckley building and testing using the Makefile certainly isn't a requirement. I think you've pointed out some very much broken cases in tests that reference files, but otherwise all tests that were not relative path dependent pass for me when I open the project in Xcode, and made sure MongoDB was running on 27017. We'll definitely update those broken tests and the documentation, thanks for pointing this out!

**Comment by kmahar** [comment]
@dlbuckley fyi, as of https://github.com/mongodb/mongo-swift-driver/commit/f71f2d2c1b85772065aa2163ca8d16a7ccc31ca7 all of the tests should now work in Xcode - see the README for updated build/test instructions and let us know if you encounter any more issues!
