### ISSUE TITLE
Question about Quick vs XCTest

### ISSUE THREAD

**Issue by phatblat** [mongodb/mongo-swift-driver#497]
Congrats on reaching 1.0!

I peeked at the `Package.swift` file and noticed this project is using Nimble with XCTest. I'm a contributor to Quick and Nimble and am curious why this project is using XCTest instead of Quick. Did you run across issues with Quick that contributed to that decision?

**Comment by kmahar** [comment]
Thanks @phatblat, and thanks for your work on Quick and Nimble!

We started using Nimble a couple of years ago very early on in driver development, so it's not fresh in my mind, but I do recall that when we tried out using Quick we were running into issues around filtering tests, and couldn't seem to figure how to do so when testing from the command line. (Just re-stumbled upon this [comment](https://github.com/Quick/Quick/issues/552#issuecomment-372382406) I made on an issue back then.) Our team does not use Xcode much and a couple of us primarily develop on Linux, so command line filtering capability was/is important for us.

**Comment by phatblat** [comment]
I will look into command line filtering with Quick as this may be possible.

Are you aware of Quick's [focused](https://github.com/phatblat/UnitTestingWithQuick/blob/master/presentation.md#-focused-test) and [excluded/disabled](https://github.com/phatblat/UnitTestingWithQuick/blob/master/presentation.md#disabled-test-quick) test features? That would help for local dev/test, but not for CI builds (as you shouldn't typically check those in).

**Comment by kmahar** [comment]
@phatblat Sorry for my delayed response, I went on vacation and lost track of this thread! Thank you for looking into that.

Those features do seem like they would be helpful to us! It's hard to recall, but I think back then we might have been using filtering in CI and in our Makefile as we had some perf tests living in the same repo which we didn't run very often. But that is no longer the case.
I think at this point given the size of our test suite and other priorities a port over to Quick is unlikely to happen anytime soon, but will certainly keep it in mind for the future as well as for any other Swift libraries we develop!

Thanks again for reaching out and for your work, we love using Nimble!

**Comment by phatblat** [comment]
No worries. I was mostly just curious and am not trying to push you to use Quick.

I'm glad I came across this repo as my company is looking at trying out MongoDB Realm and I'd like to try a Swift back end as before Node was the only option.

**Comment by kmahar** [comment]
Very cool! Please reach out if you have any questions or encounter any issues trying to use the driver.
