### ISSUE TITLE
[Memory leak] bson_malloc / swift_slowAlloc

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#516]
Apologies for only reporting memory leaks 🤷🏻‍♂️

I am not sure whether these two are related or not.

Environment:
* macOS Catalina 10.15.5
* MongoDB 4.2.7 Community (official docker container)
* Mongo driver 1.0.0
* Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53) / Target: x86_64-apple-darwin19.5.0
* Compiled in "RELEASE" mode

Unfortunately, I am not sure how to reproduce it.

![Screenshot 2020-07-27 at 14 47 10](https://user-images.githubusercontent.com/1882080/88549826-af79a980-d018-11ea-9552-777a7caaeb8f.png)

![Screenshot 2020-07-27 at 14 48 08](https://user-images.githubusercontent.com/1882080/88549839-b3a5c700-d018-11ea-9997-3b6baedbdd66.png)

**Update 31st July 2020**

**Not Fixed**

![Screenshot 2020-07-31 at 11 11 44](https://user-images.githubusercontent.com/1882080/89025416-b9542300-d31e-11ea-92c7-c030f8f77b8a.png)

![Screenshot 2020-07-31 at 11 11 54](https://user-images.githubusercontent.com/1882080/89025424-bce7aa00-d31e-11ea-8954-2986a9fe31fc.png)

**Fixed by https://github.com/mongodb/mongo-swift-driver/issues/516#issuecomment-666863404**

![Screenshot 2020-07-29 at 10 36 56](https://user-images.githubusercontent.com/1882080/88784019-6e53d780-d187-11ea-8ec9-09e9778b1b37.png)

![Screenshot 2020-07-29 at 10 37 12](https://user-images.githubusercontent.com/1882080/88784039-77dd3f80-d187-11ea-8124-39e8b0107d28.png)

![Screenshot 2020-07-29 at 10 37 28](https://user-images.githubusercontent.com/1882080/88784065-8166a780-d187-11ea-864b-1ba0450c3423.png)

![Screenshot 2020-07-29 at 10 37 47](https://user-images.githubusercontent.com/1882080/88784101-8cb9d300-d187-11ea-9f56-0ff653da17e1.png)

![Screenshot 2020-07-29 at 10 38 00](https://user-images.githubusercontent.com/1882080/88784123-95120e00-d187-11ea-8943-48891314fa6c.png)

**Comment by kmahar** [comment]
No need to apologize, we very much appreciate you reporting them!

We are looking into these, will update you when we have more info. 

One question - in the second image anyway it looks to be related to the server discovery and monitoring API. Are you using that API, and if so would you be able to provide a code sample showing how you use it? (e.g. what your event handler type or registered closure looks like.) Thanks!

**Comment by valeriomazzeo** [comment]
No that I know of. I am only using the client `MongoClient(connectionString, using: eventLoop)`. 
I am not sure what could trigger that, as I am also connecting to localhost so it's a very simple setup.

**Comment by kmahar** [comment]
We hit that code path regardless of if you have a handler registered - just helps me narrow things down a bit to know the leak is entirely based on what we are doing internally and doesn't depend on whether you are using the API. Thanks!

**Comment by valeriomazzeo** [comment]
@kmahar - It seems there are more. I am not sure whether they are related or caused by the same underlying issue.
It's totally possible I am somehow misusing the driver somehow, either way it would be nice to understand what's going on.

**Comment by kmahar** [comment]
@valeriomazzeo Thanks for the additional details. This is very concerning, I am prioritizing investigating this today and I'll update you as soon as I know anything.

**Comment by kmahar** [comment]
@valeriomazzeo Just to give an update on what I've done so far - 

I created a Vapor app using Fluent via template from the command line Vapor tool. Selected Mongo as the database, and then swapped in your Fluent library for the MongoKitten-based one that the template used. This is the classic template Todo list app (I can share the source code if you'd like). Running this with leak checking on, I was able to immediately reproduce the leaks above that involved the `BSONBinary` type (first and third images in your update) by sending a post request to add a new todo, and then querying for a list of all the todos (that triggered the leak, when transforming a document to a Todo).

I tried extracting out what seems to be the relevant bit of code from the driver, which reads out a `BSONBinary` from an existing document, into an executable, and did not encounter any leaks.

I then made a copy of the Vapor app and edited to use the same `Todo` type and routes, but directly use driver APIs along with Codable directly rather than your library. Ran with leak detection, did queries and inserts, no leaks were found.

This would seem to imply to me that something is going on in either in your library or in Fluent itself that is not releasing `BSONBinary`s being read of out of documents. I think the array-related leaks are likely the same issue. 

It may indeed be related to the subscript getter you linked to, though at least from an initial look at the implementation I did not see anything wrong with it.

I'm going to keep investigating, will update later on.

**Comment by kmahar** [comment]
@valeriomazzeo I think I've found a pretty nasty bug in Swift itself. I noticed all of the recent batch of leaks came through your `MongoDatabaseOutput.decodeNil` so I started messing around with that method.

There seems to be an issue with matching on `.none` in a switch statement. If you rewrite your `decodeNil` method like this to handle the `.none` case explicitly before the switch, the leak I found disappears:
```swift
    func decodeNil(_ key: FieldKey) throws -> Bool {
        guard let value = self.namespace[key.mongoKey] else {
            return true
        }

        switch value {
        case .undefined, .null:
            return true
        default:
            return false
        }
    }
```

This would explain your super high memory usage - it seems like any time an optional field in one of your models is being decoded (I'm guessing you probably have a model/models with optional UUIDs and arrays?), [this `decodeNil` method gets called](https://github.com/vapor/fluent-kit/blob/8a20f1dd111fa715d60e79fcfc38d8229c88392e/Sources/FluentKit/Properties/OptionalField.swift#L94) and the value retrieved from the document is leaked via the `switch`.

Here's a smaller repro of this independent of the driver (I am using a simplified `BSON` type redefined here) that the leak checker finds the leak on:

```swift
import Foundation

enum BSON {
    indirect case array([BSON])
    case datetime(Date)
    case int32(Int32)
}

func doSomething() {
    let v: BSON? = .array([.int32(1)])
    switch v {
    case .none:
        print("it's none")
   case .datetime:
       print("it's a date")
    default:
        print("default")
    }
}

do {
    doSomething()
}

print("done")

sleep(10)
```

I'm going to try to boil down that example to be even simpler and file a Swift bug report tomorrow. 

For now I would suggest switching to the non-leaky version of the method I pasted above and perhaps auditing for any other usages of a switch on `.none`.

I don't think this explains the initial two leaks, you reported but hopefully making that change will at least greatly reduce your memory usage.

**Comment by valeriomazzeo** [comment]
Wow ... who would have thought.

I'll make those changes and run an audit of the project again.

Thank you very much, and apologies to waste your time on something that turned out to be not strictly related to the mongo driver.

**Comment by valeriomazzeo** [comment]
@kmahar - I can confirm that avoid using a `switch` directly on optional `BSON` value (when `.none`) fixes some of the memory leaks. I have updated the issue description. The ones that are still not fixed are the ones in the first 4 screenshots from the top.

**Comment by kmahar** [comment]
Glad to hear that and thank you for the updates! I'm going to continue investigating the remaining leaks, and I will keep you posted. BTW you are connected to a standalone MongoDB server right, not a replica set?

**Comment by valeriomazzeo** [comment]
Just testing on localhost connecting to an official docker container. MongoDB 4.2.7 Community.

**Comment by kmahar** [comment]
Hi @valeriomazzeo, thanks for your patience. I've still been unable to reproduce this, even though testing via breakpoints my application seems to hit the exact driver code paths you are seeing the leaks on.
That said, I am suspicious about the use of `String.cString` in the [relevant line where the leaked memory is allocated](https://github.com/mongodb/mongo-swift-driver/blob/ec67468132743919e90a34a76073afcc4a13355e/Sources/MongoSwift/BSON/BSONDocumentIterator.swift#L59), as it's not necessary - we can just pass in `key` directly.

Any chance it's possible for you to try out a fix yourself and see if the issue persists, given my inability to repro the leak? I've put the very small change up on a branch here - it's identical to 1.0.1 just with the additional change: https://github.com/mongodb/mongo-swift-driver/tree/leak-fix

A relevant note, we are planning to release a 1.1 version of the driver in ~2 weeks that brings in an entirely [new BSON library](https://github.com/mongodb/swift-bson), written in pure Swift. The `BSONDocumentIterator` type which seems to be involved in the leak has been completely rewritten, so there's a decent chance that this issue will go away then, if not sooner.

**Comment by valeriomazzeo** [comment]
No problem, thank you for looking into it.

>A relevant note, we are planning to release a 1.1 version of the driver in ~2 weeks that brings in an entirely new BSON library, written in pure Swift (though with an identical public API to the current BSON implementation). The BSONDocumentIterator type which seems to be involved in the leak has been completely rewritten, so there's a decent chance that this issue will go away then, if not sooner.

Agreed. If that's the case then it's probably a better use of your time to focus on the new BSON library release and audit that directly. I am confident that would be way more solid in regards to memory leaks.

**Comment by piers12** [comment]
Any update on when version 1.1 with the Pure Swift BSON library will be getting released?

**Comment by kmahar** [comment]
Hi @piers12, while we've completed the initial implementation of that library, we identified some performance degradation compared to the current C-based library and we are working to bring the performance closer to that of the C-based library before releasing it to ensure the upgrade to v1.1 is a smooth experience.

Are you experiencing the same leak?

**Comment by piers12** [comment]
Hi @kmahar 
I haven't been experiencing the same leak. Was just curious about how things were progressing.
Thanks

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/SWIFT-1024

**Comment by kmahar** [comment]
@valeriomazzeo, today someone raised what I think is a related issue in #571. While it occurred on Linux (and that is where I was able to reproduce it), the user noted that they also saw a much smaller leak of the same method on macOS. 

I ended up putting out a patch release for that issue, v1.0.2, which _may_ fix the leak you described here.

In any case, we had to table the work on the new BSON library for a bit, but we are focusing on it again now and aiming to wrap up the performance work and get out v1.1 of the driver in a few weeks, so even if v1.0.2 does not fix the remaining leak you described here I am hoping v1.1 will.

**Comment by valeriomazzeo** [comment]
Thanks @kmahar, will update to this patch release and see if the situation improves. We have been experiencing massive memory leaks on linux (docker container), for several months now. I wasn't able to pin it down to either vapor or the mongo driver. Hopefully this helps.

**Comment by valeriomazzeo** [comment]
@kmahar I would say that looks much better now 🎉
![Screenshot 2021-01-14 at 11 38 22 copy](https://user-images.githubusercontent.com/1882080/104580549-b5faec80-565d-11eb-8f20-c393a14b4e40.png)

**Comment by kmahar** [comment]
Hello! We've released version 1.1 of the driver now which swaps in the new pure Swift BSON library for the C-based one. I am hoping this resolves any remaining memory leak issues. Would love for you to try it out and let us know how it goes.

**Comment by valeriomazzeo** [comment]
@kmahar - The fluent driver tests are all passing. Although, I wrote some specific tests on my application some time ago, to ensure backwards compatibility when reading data written with an older version of the driver; and those are failing.

Obviously, something has changed behind the scenes, it could be a bug in the new BSON library, or it could be that my tests are no valid for whatever reason. Either way, I would be grateful if you could take a look.

```swift
    func testBackwardCompatibleDecoding() throws {
        let app = try Application(.testing).prepareMongoLocal("ModelTests")
        defer {
            try? app.mongoDatabase?.mongoLocalDrop("ModelTests")
            app.shutdown()
        }

        let document = try BSONDocument(fromJSON:
            """
            {"_id":{"$binary":"CjJecTUqS7y4e3X8Cz4ZcQ==","$type":"4"},"userId":"[REDACTED]","programId":"[REDACTED]","fromBeginning":true,"createdAt":{"$date":"2020-05-04T13:40:00.651Z"},"updatedAt":{"$date":"2020-05-04T13:40:00.651Z"}}
            """
        )

        try app.mongoDatabase?.mongoInsert(document, as: Model.self).wait()

        let id = UUID(uuidString: "0a325e71-352a-4bbc-b87b-75fc0b3e1971")

        let model = try Model
            .find(id, on: app.mongoDatabase!)
            .unwrap(or: Abort(.notFound))
            .wait()

        XCTAssertEqual(model.id, id)
        XCTAssertEqual(model.userId, "[REDACTED]")
        XCTAssertEqual(model.programId, "[REDACTED]")
        XCTAssertTrue(model.fromBeginning)
        XCTAssertEqual(model.createdAt, Date(mongo: "2020-05-04T13:40:00.651Z")!)
        XCTAssertEqual(model.updatedAt, Date(mongo: "2020-05-04T13:40:00.651Z")!)
    }
```

```
caught error: "dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "_id: Expected extended JSON wrapper object, but got extra keys: [\"$type\": ExtrasJSON.JSONValue.string(\"4\"), \"$binary\": ExtrasJSON.JSONValue.string(\"CjJecTUqS7y4e3X8Cz4ZcQ==\")]", underlyingError: nil))"
```

**Comment by patrickfreed** [comment]
The issue here is that we omitted [Extended JSON v1 (legacy)](https://docs.mongodb.com/manual/reference/mongodb-extended-json-v1/) parsing from the new BSON library, whereas libbson had support for it. In [Extended JSON v2](https://docs.mongodb.com/manual/reference/mongodb-extended-json/), the format for a BSON binary type is the following:
```json
{ "$binary" : { "base64": "<base64 string>", "subType": "0x4" } }
```
Note the use of a subdocument instead of two top level keys. 

This was definitely an oversight, so thank you for reporting this! I've filed SWIFT-1126 to track the work for fixing this, and we should have it out in a patch release shortly. In the meantime, you could update the extended JSON string in the test to use the v2 format, assuming that wouldn't negate the purpose of the test.

**Comment by valeriomazzeo** [comment]
Thanks @patrickfreed.

>... assuming that wouldn't negate the purpose of the test.

I think it would, as we have a production MongoDB with data stored in that way by the previous version of the driver. It's essential that the new version of the driver is able to decode that data, otherwise we will have to run migrations, etc.

**Comment by patrickfreed** [comment]
We just published version `3.0.1` of SwiftBSON, which should fix the issue you're seeing in that test. Please let us know if anything else comes up. Since it's just a patch release of SwiftBSON, you can just run `swift package update` without modifying your `Package.swift` and it should bring it in.

As a side note: the issue here is specifically with the format of the extended JSON string used in the test, not with any actual BSON data stored in a database, which the driver should handle fine.

**Comment by valeriomazzeo** [comment]
Thanks @patrickfreed - tests are green ✅ with the latest version of `SwiftBSON`!

**Comment by kmahar** [comment]
Glad to hear that @valeriomazzeo ! Have you been experiencing any more memory leak issues, or can this issue be closed out?

**Comment by valeriomazzeo** [comment]
Will monitor the memory usage during next week and report here 👍

**Comment by valeriomazzeo** [comment]
I have been running this for a week now. Situation seem to have improved to a reasonable level. Thanks all.

![Screenshot 2021-04-12 at 11 54 48](https://user-images.githubusercontent.com/1882080/114376443-eb907280-9b85-11eb-83b0-022733334dce.png)
