### ISSUE TITLE
iOS usage not clear

### ISSUE THREAD

**Issue by BildPeter** [mongodb/mongo-swift-driver#52]
It is not clear how to use the mongo-swift-driver in a iOS project, as the mongoc and BSON libraries are not build for iOS

`Could not build Objective-C module 'libmongoc'`

I included the plain mongoc header & source in the xCode project, but they are not being compiled. 
''mongoc.h' file not found'
Also setting the header search path does not solve the proplem

**Comment by rurunuela** [comment]
Up same problem

**Comment by mbroadst** [comment]
@BildPeter @rurunuela @alicin the Cocoapod will be updated within the month to provide a fully integrated solution using our pre-compiled Mobile SDKs. You can track progress of this [here](https://jira.mongodb.org/browse/SWIFT-205)!
