### ISSUE TITLE
Update Podspec

### ISSUE THREAD

**Issue by greenmood** [mongodb/mongo-swift-driver#532]
Latest version of MongoSwift I found on Cocoapods is 0.1.3
https://github.com/CocoaPods/Specs/blob/69dbb98324458b46d83854f318fee11d9b637ae4/Specs/4/5/d/MongoSwift/0.1.3/MongoSwift.podspec.json

Do MongoSwift support update using Cocoapods to the latest version?

**Comment by kmahar** [comment]
Hi @greenmood, we no longer support installing the driver via Cocoapods, only via Swift Package Manager.
