### ISSUE TITLE
Documentation: how to sort all records after running collection.find()

### ISSUE THREAD

**Issue by gurugeek** [mongodb/mongo-swift-driver#551]
### Swift version

5.4

### Operating system

OS X Big Sour

### Driver version
1.0.1

## What is the problem? 

This is not a bug but a documentation enhancement. I moved from 0.2.0 to the latest 1.0.1 version of the driver. I managed to make it work fine both on Mac OS X and Linux for deployment.  I just can't locate anywhere a way to sort documents after retriving them all from the database:

`  let documents = try collection.find()`

adding .sort({_id:-1}) doesn't work so perhaps the readme should be updated (I assume this is a very common use case). In any case thanks for letting me know how sort the results.

**Comment by gurugeek** [comment]
I figured it out !

**Comment by kmahar** [comment]
@gurugeek Glad you figured it out! 

Just to record this for the future benefit of anyone reading, you can accomplish this using the `sort` option in `FindOptions`, e.g.
```swift
var opts = FindOptions()
opts.sort = ["_id": -1]
let sortedCursor = try collection.find(options: opts)
for doc in sortedCursor {
    // provides docs in sorted order
}
```

**Comment by gurugeek** [comment]
@kmahar thank you, I also think it might be good to add to the documentation an example with both options and filters. I used this

```

        let sort: BSONDocument = ["_id": -1]
        let options = FindOptions(limit: 10, sort: sort)
        let query: BSONDocument = [ "slug": [ "$ne": "index" ] ]
        let documents = try collection.find(query,options: options)
```

probably fairly trivial but may be useful for the begginers :)

**Comment by kmahar** [comment]
@gurugeek Makes sense to me! We opened a [Jira ticket](https://jira.mongodb.org/browse/SWIFT-1034) to track the work, one of us will pick it up soon 🙂
