### ISSUE TITLE
SWIFT-1038 ⁃ is this work if my mongodb is in realm?

### ISSUE THREAD

**Issue by yogendra-leocan** [mongodb/mongo-swift-driver#558]
My mongodb is in realm, so this syntax work for me?

Please reply me as soon as possible.

**Comment by agolin95** [comment]
Hi @yogendra-leocan, unfortunately you will not be able to use the Swift Driver with your Realm instance of MongoDB. Please see this documentation about our Realm SDK for iOS for more detailed information about how to get started with Realm and Swift: https://docs.mongodb.com/realm/ios
