### ISSUE TITLE
README.MD: link to Vapor example broken

### ISSUE THREAD

**Issue by pfurbacher** [mongodb/mongo-swift-driver#641]
In the README.MD file for this project, find the following sentence.

```The Examples/ directory contains sample projects that use the driver with Kitura, Vapor, and Perfect.```

Clicking on ```Vapor``` results in a 404.

The link to the Vapor example points to ```https://github.com/mongodb/mongo-swift-driver/tree/main/Examples/ComplexVaporExample``` 

The last member of that path should read ```VaporExample```, not ```ComplexVaporExample```.

**Comment by agolin95** [comment]
Thank you for the report @pfurbacher, PR has been merged!
