### ISSUE TITLE
SWIFT-1438 ⁃ Change @available attribute on async/await features

### ISSUE THREAD

**Issue by atultw** [mongodb/mongo-swift-driver#720]
### Swift version
```
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.2 clang-1300.0.29.30)
Target: x86_64-apple-macosx11.0
```

### Operating system
```
Darwin Someones-MBP 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
```

## What is the problem? 

Apple has released an Xcode update enabling async/await on macOS older than 12. 

https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes#Swift

The codebase includes a lot of `@available(macOS 12, *)` attributes on the async features. Given the new update we should change the `12` to `10.15`.

https://github.com/mongodb/mongo-swift-driver/search?q=%40available%28mac

Should I go ahead and make a PR?

**Comment by atultw** [comment]
Related to https://github.com/apple/swift-nio/pull/2004

That issue was resolved in a new version. Updating `swift-nio` dependency to `2.36.0` allows the `@available` here to be updated too.

**Comment by bajanam** [comment]
@atultw  Thanks for the analysis and PR.  The team is off for the holidays but we will review this based our development capacity when they return.

**Comment by bajanam** [comment]
This was fixed PR# 21
