### ISSUE TITLE
SWIFT-1607 ⁃ /mongo-swift-driver/Sources/MongoSwift/MongoCursor.swift: runtime: Threading Issues: Data race in closure #1 @Sendable () async throws -> () in MongoSwift.MongoCursor.deinit at 0x7b54000cff80

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#767]
## Describe the bug

I am unsure whether this is caused by an improper use of the driver, by vapor, my vapor-driver or both. 
Although, this same check has been running without issues on v1.2.0.

Any help is appreciated :)

![Screenshot 2022-07-21 at 15 18 45](https://user-images.githubusercontent.com/1882080/180223271-e76e61fb-0035-466c-91f2-e375cb8831e7.png)

Full log visible on this travis-ci build https://app.travis-ci.com/github/asensei/vapor-fluent-mongo/jobs/577364909

## Versions/Environment
- Swift 5.6
- macOS / Xcode 13.4
- 1.3.1
- 5.0.9
- standalone mongo docker container

**To Reproduce**
1. Clone https://github.com/asensei/vapor-fluent-mongo/tree/feature/update (`feature/update` branch)
2. `swift test --sanitize=thread`

**Comment by kmahar** [comment]
Hey @valeriomazzeo thanks for getting in touch about this! 

In Swift 5.5 and 5.6 there are unfortunately some known shortcomings with TSan not understanding the new concurrency model yet. There's some various discussion about that on the forums where people have encountered similar TSan warnings involving `swift::runJobInEstablishedExecutorContext`: [here](https://forums.swift.org/t/concurrency-testing-vs-thread-sanitizer/53308), [here](https://forums.swift.org/t/tsan-with-task-concurrency-warnings/57775), also apple/swift#57749. 

I'm indeed able to reproduce this warning with Xcode 13.4. However, a couple of the issues I link above mention these issues are gone in Xcode 14, and when I try running your tests with Xcode 14 beta 3 I get no thread sanitizer warnings anymore. So my inclination is to say that these are just false positives that should go away with Swift 5.7. What do you think?

**Comment by valeriomazzeo** [comment]
You seem to know way more than me on the topic, hence why I asked! :)

It does sound like they are false positives, especially if they are gone in Xcode 14.

Happy to close the issue, and thanks for your help!
