### ISSUE TITLE
SWIFT-1706 ⁃ async iterator performance

### ISSUE THREAD

**Issue by fdstevex** [mongodb/mongo-swift-driver#777]
## Versions/Environment
1. What version of Swift are you using? 5.7.2
2. What operating system are you using? Darwin Kernel Version 22.2.0 (macOS 13.1)
3. What versions of the driver and its dependencies are you using? `main`
4. What version of MongoDB are you using? 5.0.11
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)? local standalone

## Describe the bug
I tried an async iterator and found it slower than forEach.

**To Reproduce**
```swift
            let start = Date()
            var count = 0
            for try await doc in try await collection.find() {
                if let title = doc["title"]?.stringValue {
                    count += 1
                }
            }
            log.info("Scanned \(count) documents in \(-start.timeIntervalSinceNow) seconds")
```

For my test database (133k documents, average size about 1k) this ran consistently around 19 seconds.

What I was using before:

```swift
            let start = Date()
            var count = 0
            let future = try await collection.find().forEach { doc in
                if let title = doc["title"]?.stringValue {
                    count += 1
                }
            }
            try await future.get()
            log.info("Scanned \(count) documents in \(-start.timeIntervalSinceNow) seconds")
```

This completes in about 6.6 seconds.  Both scan the same number of documents.

I don't know what to attribute this to, but wanted to raise it as a potential problem since it seems counterintuitive.

**Comment by isabelatkinson** [comment]
Hi @fdstevex, thanks for opening this issue! The team does not currently have the capacity to investigate this performance discrepancy, but we've filed SWIFT-1706 for future consideration. Feel free to follow that ticket for updates.

**Comment by isabelatkinson** [comment]
The MongoDB Swift Driver is no longer being actively developed (see [Development Pause](https://github.com/mongodb/mongo-swift-driver#development-pause)). We will reopen and investigate this issue if development resumes in the future.
