### ISSUE TITLE
SWIFT-1707 ⁃ AWS Lambda example

### ISSUE THREAD

**Issue by onelogapp** [mongodb/mongo-swift-driver#778]
In the AWS Lambda Function example on the main branch the code initialises the mongo client with a new ELG and adds shutdown code to deinit of the LambdaHandler

Questions:

1) is it better/worse/wrong/ok to use the `LambdaInitializationContext`'s event loop?
```
let mongoClient: MongoClient
required init(context: LambdaInitializationContext) async throws {
   self.mongoClient = try MongoClient("...", using: context.eventLoop)
}
```

2) Is is better/worse/wrong/ok to register a terminator on the `LambdaInitializationContext's context rather than using deinit?
```
let mongoClient: MongoClient

required init(context: LambdaInitializationContext) async throws {
    
    self.mongoClient = ...
    
    context.terminator.register(name: "MongoDBShutDown") { [weak self] eventloop in
        try? self?.mongoClient.syncClose()
        cleanupMongoSwift()
        return eventloop.makeSucceededVoidFuture()
    }
}
```

**Comment by isabelatkinson** [comment]
The MongoDB Swift Driver is no longer being actively developed. (see [Development Pause](https://github.com/mongodb/mongo-swift-driver#development-pause)). We will reopen and investigate this issue if development resumes in the future.
