### ISSUE TITLE
Lifecycle of `MongoClient`

### ISSUE THREAD

**Issue by NikolayJuly** [mongodb/mongo-swift-driver#783]
## Versions/Environment
1. What version of Swift are you using? - 5.9, but issue reproducable for many swift versions
2. What operating system are you using? - runnin in slim docker image `swift:5.9.1-jammy-slim`
3. What versions of the driver and its dependencies are you using? - 1.3.1
4. What version of MongoDB are you using? - container `mongo:6.0.5-jammy`
5. What is your MongoDB topology ? - standalone

## Describe the bug
I have situation when I need to process thousands of documents in some periodic jobs. And I had issue that memory usage constantly growin during this tasks(might be expected) and do not go down after job completed(not expected).

I did some tests and I figured out, that if I will re-use `MongoClient` between this long running processing operations - I'm getting constantly growing memory usage(70k documents lead to 150Mb of RAM). But if I will create `MongoClient` per processing operation - and make sure I call `close()` in the end of operation, memory usage returns to normal.

I expected that `MongoClient` is log living object, that can and should be used during whole life cycle of application. But it appears that they hold some decoded document data, even after I don't use those documents anymore. I think documentation should state this, if this is the case. Because I treated it as URLSession, which you create once or uses singleton.

Funny part, I can't reproduce the same on macos, on macOS after spike I see that memory usage dropped to 40MB, from 120MB spike. Even without `MongoClient.close()`.

**Steps to reproduce the behavior:**
1. Do many `try await collection.find().toArray()` calls to db and receive ~70K `BSONDocument`
2. Then use `BSONDecoder()` to decode document to your own type/struct. Make sue to have many 4-5 string fields in your codable struct
3. See that memory grown by 150 MB and not gowing down, and you not reference any of the data anymore. Checked memory graph, so no memory leaks on my side.
4. And then call `MongoClient.close()`
5. You will see that 150 MB of RAM usage is gone.

**Comment by isabelatkinson** [comment]
The MongoDB Swift Driver is no longer being actively developed. (see [Development Pause](https://github.com/mongodb/mongo-swift-driver#development-pause)). We will reopen and investigate this issue if development resumes in the future.
